version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: has123456
      POSTGRES_DB: aws_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create_table.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    restart: always
    depends_on:
      - db
    devices:
      - "/dev/ttyS0:/dev/ttyS0"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: aws_db
      DB_USER: postgres
      DB_PASSWORD: has123456
    ports:
      - "5010:5010"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /media/pi:/mnt/usb:rw 

volumes:
  pgdata:
